### ISSUE TITLE
Make this a template repo

### ISSUE THREAD

**Issue by CDDelta** [ianrose/deventy#18]
Thank you for your work on this great starter! I have already started using it for my site and am loving it.

Is it possible for you to make this a template repo? It would make using this template a lot easier for people in the future! You can find out how to do that [here](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository) if you're unsure. It's just a toggle in the settings.

**Comment by ianrose** [comment]
Done! 😄
